version: '3'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: root,
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testes   
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
